services:
  ip-bot:
    container_name: ip_bot # Name of the container
    network_mode: host  
    environment:
      - HOST_NAME=${HOST_NAME}
      - TOKEN=${TOKEN}
      - SEND_CHANNEL=${SEND_CHANNEL}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
    build: .
    restart: unless-stopped
